### ISSUE TITLE
Érror: 'frame_time' is not defined

### ISSUE THREAD

**Issue by Jgerardopine** [H21lab/json2pcap#3]
Hi, 

  I tried to use your code, but I get the following error:

`Traceback (most recent call last):
  File "./json2pcap.py", line 645, in <module>
    new_packet.time = float(frame_time)
NameError: name 'frame_time' is not defined
`
The only thing I changed into my code was the `#!/usr/bin/python3`, not sur eif this supports python3. this is the ocmmand I run:

`/json2pcap.py -i ~/pcaps/dtag/poc/sample_pcap/test3.json -o test.pcap`

Is there an additional parameter I should pass? I only intend to convert back a dissected json into pcap.

**Comment by H21lab** [comment]
Thank you for reporting this. The error should be fixed in this commit https://github.com/H21lab/json2pcap/commit/c219ef6b8727327725854078d1ff355102f87c13.

The frame_time is present only in tshark -T json -x output and not in tshark -T jsonraw output. If you would like to preserve time from original pcap, use -T json -x. If the frame_time is not present (for -T jsonraw), the json2pcap script will use the current time in output pcap.
